export interface ToolData {
  title: string
  description: string
  icon: string
  href: string
  isNew: boolean
  category: string
}

export const tools: ToolData[] = [
  // === Image Tools (10) ===
  { title: 'Image Compress', description: 'Reduce image file size while keeping quality', icon: '🗜️', href: '/tools/image-compress', isNew: false, category: 'image' },
  { title: 'Image Resize', description: 'Resize and crop images to exact dimensions', icon: '📐', href: '/tools/image-crop', isNew: false, category: 'image' },
  { title: 'Format Converter', description: 'Convert between JPG, PNG, WebP, GIF, AVIF', icon: '🔄', href: '/tools/format-converter', isNew: false, category: 'image' },
  { title: 'Image OCR', description: 'Extract text from images (browser-based)', icon: '🖼️', href: '/tools/image-ocr', isNew: false, category: 'image' },
  { title: 'QR Code Generator', description: 'Generate QR codes with custom colors', icon: '▣', href: '/tools/qr-code', isNew: false, category: 'image' },
  { title: 'Image Splitter', description: 'Split images into rows and columns', icon: '✂️', href: '/tools/image-splitter', isNew: true, category: 'image' },
  { title: 'Image to PDF', description: 'Convert images to PDF documents', icon: '📷', href: '/tools/image-to-pdf', isNew: true, category: 'image' },
  { title: 'Color Extractor', description: 'Extract dominant colors from photos', icon: '🎨', href: '/tools/color-extractor', isNew: true, category: 'image' },
  { title: 'QR Code Reader', description: 'Decode QR codes from uploaded images', icon: '📷', href: '/tools/qr-reader', isNew: true, category: 'image' },
  { title: 'Favicon Generator', description: 'Generate favicon icons from images', icon: '⭐', href: '/tools/favicon-generator', isNew: true, category: 'image' },

  // === PDF Tools (9) ===
  { title: 'PDF Merge', description: 'Combine multiple PDFs into one document', icon: '📑', href: '/tools/pdf-merge', isNew: false, category: 'pdf' },
  { title: 'PDF to PPT', description: 'Convert PDF pages into PowerPoint slides', icon: '📽️', href: '/tools/pdf-to-ppt', isNew: false, category: 'pdf' },
  { title: 'PDF Compress', description: 'Reduce PDF file size online', icon: '📦', href: '/tools/pdf-compress', isNew: false, category: 'pdf' },
  { title: 'Doc Converter', description: 'Convert Word ↔ PDF with images preserved', icon: '📄', href: '/tools/doc-converter', isNew: false, category: 'pdf' },
  { title: 'PDF Split', description: 'Extract specific pages from a PDF file', icon: '✂️', href: '/tools/pdf-split', isNew: true, category: 'pdf' },
  { title: 'PDF to JPG', description: 'Convert PDF pages to high-quality JPG images', icon: '🖼️', href: '/tools/pdf-to-jpg', isNew: true, category: 'pdf' },
  { title: 'PDF to Text', description: 'Extract text content from PDF files', icon: '📝', href: '/tools/pdf-to-text', isNew: true, category: 'pdf' },
  { title: 'PDF Password', description: 'Add or remove PDF password protection', icon: '🔐', href: '/tools/pdf-password', isNew: true, category: 'pdf' },
  { title: 'PDF Metadata', description: 'View and edit PDF document metadata', icon: '📋', href: '/tools/pdf-metadata', isNew: true, category: 'pdf' },

  // === AI Tools (30) ===
  { title: 'AI Text Summary', description: 'Summarize articles with AI in seconds', icon: '🤖', href: '/tools/ai-summary', isNew: false, category: 'ai' },
  { title: 'AI Translator', description: 'Translate text between 20+ languages', icon: '🌐', href: '/tools/ai-translator', isNew: false, category: 'ai' },
  { title: 'AI Rewriter', description: 'Rewrite text in formal, casual, or marketing tone', icon: '✍️', href: '/tools/ai-rewriter', isNew: false, category: 'ai' },
  { title: 'AI Chat', description: 'Chat with AI for help with any task', icon: '💬', href: '/tools/ai-assistant', isNew: false, category: 'ai' },
  { title: 'AI Grammar Check', description: 'Check spelling, grammar, and punctuation', icon: '✓', href: '/tools/ai-grammar', isNew: false, category: 'ai' },
  { title: 'AI Email Generator', description: 'Generate professional emails instantly', icon: '✉️', href: '/tools/ai-email', isNew: false, category: 'ai' },
  { title: 'AI Title Generator', description: 'Generate catchy titles for blogs & videos', icon: '🏷️', href: '/tools/ai-title', isNew: false, category: 'ai' },
  { title: 'AI Keyword Extractor', description: 'Extract keywords for SEO optimization', icon: '🔑', href: '/tools/ai-keywords', isNew: false, category: 'ai' },
  { title: 'AI Blog Generator', description: 'Generate blog outlines and full posts', icon: '📝', href: '/tools/ai-blog', isNew: false, category: 'ai' },
  { title: 'AI Pros & Cons', description: 'Get balanced analysis of any decision', icon: '⚖️', href: '/tools/ai-pros-cons', isNew: false, category: 'ai' },
  { title: 'AI Cover Letter', description: 'Generate cover letters with AI', icon: '✉️', href: '/tools/cover-letter', isNew: false, category: 'ai' },
  { title: 'AI Hashtag Generator', description: 'Generate hashtags for social media', icon: '#', href: '/tools/ai-hashtags', isNew: false, category: 'ai' },
  { title: 'AI Bio Generator', description: 'Generate bios for any platform', icon: '👤', href: '/tools/ai-bio', isNew: false, category: 'ai' },
  { title: 'AI Copywriter', description: 'Generate ad copy and descriptions', icon: '✍️', href: '/tools/ai-copy', isNew: false, category: 'ai' },
  { title: 'AI Readability Checker', description: 'Analyze and improve text readability', icon: '📊', href: '/tools/ai-readability', isNew: false, category: 'ai' },
  { title: 'AI Interview Questions', description: 'Generate questions for any role', icon: '💼', href: '/tools/ai-interview', isNew: false, category: 'ai' },
  { title: 'AI Flashcard Generator', description: 'Turn text into study flashcards', icon: '📇', href: '/tools/ai-flashcards', isNew: false, category: 'ai' },
  { title: 'AI Resume Builder', description: 'Build a resume and download as PDF', icon: '📄', href: '/tools/resume-builder', isNew: false, category: 'ai' },
  { title: 'AI Story Generator', description: 'Generate creative stories with AI', icon: '📖', href: '/tools/ai-story', isNew: true, category: 'ai' },
  { title: 'AI Poem Generator', description: 'Write poems on any topic with AI', icon: '📝', href: '/tools/ai-poem', isNew: true, category: 'ai' },
  { title: 'AI Code Explainer', description: 'Get plain-English explanations of code', icon: '💡', href: '/tools/ai-code-explainer', isNew: true, category: 'ai' },
  { title: 'AI Product Description', description: 'Generate product descriptions for e-commerce', icon: '🏷️', href: '/tools/ai-product-desc', isNew: true, category: 'ai' },
  { title: 'AI Slogan Generator', description: 'Create catchy slogans for your brand', icon: '💬', href: '/tools/ai-slogan', isNew: true, category: 'ai' },
  { title: 'AI Social Media Post', description: 'Generate engaging social media content', icon: '📱', href: '/tools/ai-social', isNew: true, category: 'ai' },
  { title: 'AI Thank You Note', description: 'Write thoughtful thank-you messages', icon: '💌', href: '/tools/ai-thanks', isNew: true, category: 'ai' },
  { title: 'AI Email Reply', description: 'Generate smart email replies quickly', icon: '↩️', href: '/tools/ai-email-reply', isNew: true, category: 'ai' },
  { title: 'AI Birthday Wish', description: 'Create personalized birthday greetings', icon: '🎂', href: '/tools/ai-birthday-wish', isNew: true, category: 'ai' },
  { title: 'AI Love Letter', description: 'Write romantic love letters with AI', icon: '❤️', href: '/tools/ai-love-letter', isNew: true, category: 'ai' },
  { title: 'AI Speech Writer', description: 'Write speeches for any occasion', icon: '🎤', href: '/tools/ai-speech', isNew: true, category: 'ai' },
  { title: 'AI FAQ Generator', description: 'Generate FAQs from any content', icon: '❓', href: '/tools/ai-faq', isNew: true, category: 'ai' },
  { title: 'AI Learning Path', description: 'Create personalized learning roadmaps', icon: '📚', href: '/tools/ai-learning', isNew: true, category: 'ai' },

  // === Developer Tools (27) ===
  { title: 'Citation Generator', description: 'MLA, APA & Chicago citations', icon: '📚', href: '/tools/citation-generator', isNew: false, category: 'dev' },
  { title: 'Loan Calculator', description: 'Loan payments & compound interest', icon: '🏠', href: '/tools/loan-calculator', isNew: false, category: 'dev' },
  { title: 'Invoice Generator', description: 'Create invoices and download PDF', icon: '📋', href: '/tools/invoice-generator', isNew: false, category: 'dev' },
  { title: 'AI Regex Generator', description: 'Generate regex from plain English', icon: '🔍', href: '/tools/ai-regex', isNew: false, category: 'dev' },
  { title: 'AI SQL Generator', description: 'Natural language to SQL queries', icon: '💾', href: '/tools/ai-sql', isNew: false, category: 'dev' },
  { title: 'AI Code Converter', description: 'Convert code between 19 languages', icon: '🔄', href: '/tools/ai-code-convert', isNew: false, category: 'dev' },
  { title: 'JSON Formatter', description: 'Format, validate & minify JSON data', icon: '{}', href: '/tools/json-formatter', isNew: false, category: 'dev' },
  { title: 'Base64 Encoder', description: 'Encode text/files or decode Base64', icon: '🔐', href: '/tools/base64', isNew: false, category: 'dev' },
  { title: 'URL Encoder', description: 'Encode & decode URLs and query params', icon: '🌐', href: '/tools/url-encode', isNew: false, category: 'dev' },
  { title: 'UUID Generator', description: 'Generate UUID v4/v7 in bulk', icon: '🔢', href: '/tools/uuid-generator', isNew: false, category: 'dev' },
  { title: 'Password Generator', description: 'Generate strong, secure passwords', icon: '🔑', href: '/tools/password-generator', isNew: false, category: 'dev' },
  { title: 'Diff Checker', description: 'Compare text and code differences', icon: '⇔', href: '/tools/diff-checker', isNew: false, category: 'dev' },
  { title: 'Data Converter', description: 'Convert between JSON and YAML', icon: '⇄', href: '/tools/data-converter', isNew: false, category: 'dev' },
  { title: 'Case Converter', description: 'Convert text between 11 case formats', icon: 'Aa', href: '/tools/case-converter', isNew: false, category: 'dev' },
  { title: 'Markdown Editor', description: 'Write Markdown with live preview', icon: '📝', href: '/tools/markdown-editor', isNew: false, category: 'dev' },
  { title: 'Random Tools', description: 'Number, dice, coin, lottery, choices', icon: '🎲', href: '/tools/random-tools', isNew: false, category: 'dev' },
  { title: 'Unit Converter', description: 'Length, weight, temp, area, volume, more', icon: '📏', href: '/tools/unit-converter', isNew: false, category: 'dev' },
  { title: 'Regex Tester', description: 'Test regex patterns with live highlighting', icon: '🔍', href: '/tools/regex-tester', isNew: false, category: 'dev' },
  { title: 'Code Beautifier', description: 'Format & minify HTML, CSS, JavaScript', icon: '✨', href: '/tools/code-beautifier', isNew: false, category: 'dev' },
  { title: 'CSS Gradient Generator', description: 'Create beautiful CSS gradients visually', icon: '🌈', href: '/tools/gradient-generator', isNew: true, category: 'dev' },
  { title: 'CSS Box Shadow', description: 'Generate CSS box-shadow effects visually', icon: '🔲', href: '/tools/box-shadow', isNew: true, category: 'dev' },
  { title: 'HTML Preview', description: 'Write and preview HTML in real-time', icon: '🌐', href: '/tools/html-preview', isNew: true, category: 'dev' },
  { title: 'IP Lookup', description: 'Find your IP address and location details', icon: '🌍', href: '/tools/ip-lookup', isNew: true, category: 'dev' },
  { title: 'Color Palette Generator', description: 'Generate harmonious color palettes', icon: '🎨', href: '/tools/color-palette', isNew: true, category: 'dev' },
  { title: 'Lorem Ipsum Generator', description: 'Generate placeholder text for designs', icon: '📝', href: '/tools/lorem-ipsum', isNew: true, category: 'dev' },
  { title: 'Timestamp Converter', description: 'Convert between timestamps and dates', icon: '⏰', href: '/tools/timestamp-converter', isNew: true, category: 'dev' },
  { title: 'HTML Entity Encoder', description: 'Encode/decode HTML entities safely', icon: '🔣', href: '/tools/html-entities', isNew: true, category: 'dev' },
  { title: 'BMI Calculator', description: 'Calculate body mass index (BMI)', icon: '⚖️', href: '/tools/bmi-calculator', isNew: true, category: 'dev' },
  { title: 'Percentage Calculator', description: 'Calculate percentages quickly', icon: '💯', href: '/tools/percentage-calculator', isNew: true, category: 'dev' },
  { title: 'Date Calculator', description: 'Calculate date differences and add days', icon: '📅', href: '/tools/date-calculator', isNew: true, category: 'dev' },
  { title: 'Tip Calculator', description: 'Calculate restaurant tips and split bills', icon: '💰', href: '/tools/tip-calculator', isNew: true, category: 'dev' },
  { title: 'Age Calculator', description: 'Calculate exact age in years, months, days', icon: '🎂', href: '/tools/age-calculator', isNew: true, category: 'dev' },

  // === Text Tools (12) ===
  { title: 'Word Counter', description: 'Count words, chars, sentences & reading time', icon: '📝', href: '/tools/word-counter', isNew: false, category: 'text' },
  { title: 'Reverse Text', description: 'Reverse and flip text in multiple ways', icon: '↔️', href: '/tools/reverse-text', isNew: true, category: 'text' },
  { title: 'Text Repeater', description: 'Repeat text multiple times with delimiters', icon: '🔁', href: '/tools/text-repeater', isNew: true, category: 'text' },
  { title: 'Line Sorter', description: 'Sort lines alphabetically or by length', icon: '↕️', href: '/tools/line-sorter', isNew: true, category: 'text' },
  { title: 'Palindrome Checker', description: 'Check if text reads the same backwards', icon: '🔄', href: '/tools/palindrome-checker', isNew: true, category: 'text' },
  { title: 'Unicode Converter', description: 'Convert text to Unicode escape sequences', icon: '🔤', href: '/tools/unicode-converter', isNew: true, category: 'text' },
  { title: 'Text to Slug', description: 'Convert text to URL-friendly slugs', icon: '🔗', href: '/tools/text-to-slug', isNew: true, category: 'text' },
  { title: 'Morse Code Converter', description: 'Convert text to Morse code and back', icon: '📡', href: '/tools/morse-code', isNew: true, category: 'text' },
  { title: 'Upside Down Text', description: 'Flip text upside down for fun', icon: '🙃', href: '/tools/upside-down-text', isNew: true, category: 'text' },
  { title: 'Binary Converter', description: 'Convert text to binary and binary to text', icon: '💻', href: '/tools/binary-converter', isNew: true, category: 'text' },
  { title: 'Strikethrough Text', description: 'Generate strikethrough text with Unicode', icon: '~~', href: '/tools/strikethrough-text', isNew: true, category: 'text' },
  { title: 'Random Word Generator', description: 'Generate random words and phrases', icon: '🎲', href: '/tools/random-word', isNew: true, category: 'text' },

  // === Color Tools (6) ===
  { title: 'Color Converter', description: 'Convert between HEX, RGB, HSL with preview', icon: '🎨', href: '/tools/color-converter', isNew: false, category: 'color' },
  { title: 'Random Color Generator', description: 'Generate random colors with previews', icon: '🎲', href: '/tools/random-color', isNew: true, category: 'color' },
  { title: 'Color Contrast Checker', description: 'Check contrast ratio for accessibility', icon: '👁️', href: '/tools/contrast-checker', isNew: true, category: 'color' },
  { title: 'Color Name Finder', description: 'Find the name of any color', icon: '🏷️', href: '/tools/color-names', isNew: true, category: 'color' },
  { title: 'Gradient Generator', description: 'Create and preview CSS color gradients', icon: '🌈', href: '/tools/color-gradient', isNew: true, category: 'color' },
  { title: 'Color Blindness Sim', description: 'Simulate color blindness on images', icon: '🔍', href: '/tools/color-blindness', isNew: true, category: 'color' },
]
